- name: Copy dotfiles
  ansible.posix.synchronize:
    src: "dotfiles/"
    dest: ~/

- name: Copy firefox configuration
  ansible.posix.synchronize:
    src: "firefox/"
    dest: "~/.mozilla/firefox/{{ ff_profile_dir }}"

- name: Copy waybar configuration
  template:
    src: "waybar.j2"
    dest: "~/.config/waybar/config"
