- name: Install core packages
  community.general.pacman:
    name: "{{ packages }}"
    state: present
  become: yes

- name: Copy aurutils conf
  copy:
    src: "pacman-aur.conf"
    dest: "/etc/aurutils/pacman-aur.conf"
  become: yes
