- name: Copy pacman conf
  template:
    src: pacman.conf
    dest: /etc/pacman.conf

- name: Create directory for cache
  ansible.builtin.file:
    path: /ethereal/cache
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0777

- name: Create directory for pacman cache
  ansible.builtin.file:
    path: /ethereal/cache/pacman
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Update system
  community.general.pacman:
    update_cache: yes
    upgrade: yes

- name: Install core packages
  community.general.pacman:
    name: "{{ packages }}"
    state: present
