- name: Copy opendoas conf
  ansible.builtin.copy:
    src: doas.conf
    dest: /etc/doas.conf

- name: Copy lightdm configuration
  copy:
    src: "lightdm"
    dest: /etc/

- name: Copy brightness udev rule
  template:
    src: backlight.rules
    dest: /etc/udev/rules.d/backlight.rules
  when: mobile_device


- name: Enable lightdm
  service:
    enabled: yes
    state: started 
    name: lightdm
    runlevel: default

