[terminal]
vt = 1

# The default session, also known as the greeter.
[default_session]
command = "tuigreet --cmd /home/leela/.local/bin/sway-dbus -t -r --asterisks -g 'welcome to the garden'"
user = "greeter"
